version: '3.4'
services:
 worker:
  network_mode: host
  image: python:3.6.9-alpine3.10
  command: ash -c "apk add --no-cache build-base libcurl curl-dev; pip3 install -r requirements.txt; celery -A sampletask worker --loglevel=info"
  volumes:
    - "./app:/app"
  working_dir: /app
  restart: on-failure
    
